import turtle 

def drawflower(myTurtle, petalLength, stemLength):
	myTurtle.color("green", "blue")
	myTurtle.begin_fill()
	myTurtle.circle(petalLength, 60)
	myTurtle.left(120)
	myTurtle.circle(petalLength, 60)
	myTurtle.end_fill()
	myTurtle.left(60)
	myTurtle.begin_fill()
	myTurtle.circle(petalLength, 60)
	myTurtle.left(120)
	myTurtle.circle(petalLength, 60)
	myTurtle.end_fill()
	myTurtle.left(60)
	myTurtle.begin_fill()
	myTurtle.circle(petalLength, 60)
	myTurtle.left(120)
	myTurtle.circle(petalLength, 60)
	myTurtle.end_fill()
	myTurtle.left(60)
	myTurtle.begin_fill()
	myTurtle.circle(petalLength, 60)
	myTurtle.left(120)
	myTurtle.circle(petalLength, 60)
	myTurtle.end_fill()
	myTurtle.left(60)
	myTurtle.begin_fill()
	myTurtle.circle(petalLength, 60)
	myTurtle.left(120)
	myTurtle.circle(petalLength, 60)
	myTurtle.end_fill()
	myTurtle.left(60)
	myTurtle.begin_fill()
	myTurtle.circle(petalLength, 60)
	myTurtle.left(120)
	myTurtle.circle(petalLength, 60)
	myTurtle.end_fill()
	myTurtle.right(54)
	myTurtle.forward(stemLength)


t = turtle.Turtle()

drawflower(t, 50, 100)
x = ""
input(x)
print(x)